### ISSUE TITLE
When I try to dump dictionary I get error

### ISSUE THREAD

**Issue by ikresoft** [hhatto/pyrapidjson#12]
Assertion failed: (s != __null), function GenericStringRef, file ./pyrapidjson/include/rapidjson/document.h, line 316.

PyPy version 5.1

**Comment by hhatto** [comment]
@ikresoft 

Thank you for reporting.
Could you show the JSON data set or test code when the error occurred?
and architecture (Linux, MacOSX, etc...), too.
