### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by zii** [hhatto/pyrapidjson#14]
``` python
d = {1:1}
s = rapidjson.dumps(d)
```

Run this code, it crashed.

**Comment by hhatto** [comment]
@zii 

Thank you for bug reporting.
fix in ac97017a682ae974a9171813144ea6e60915ab2d.

Regards

**Comment by hhatto** [comment]
version 0.4.1 has been released.

https://pypi.python.org/pypi/pyrapidjson/0.4.1

**Comment by zii** [comment]
nice!
