### ISSUE TITLE
dump() returns RuntimeError: open file error

### ISSUE THREAD

**Issue by robbmcleod** [hhatto/pyrapidjson#18]
Calling dump() with an open file handle as follows:

    import rapidjson
    data = { 'foo': 'bar' }
    with open( 'tempfile.json', 'w' ) as fh:
        print( fh.fileno() )
        rapidjson.dump( data, fh )

yields:

    Traceback (most recent call last):
      File "/scratch/testrapid.py", line 12, in <module>
        rapidjson.dump( data, fh )
    RuntimeError: open file error 3

Tested on Python 3.4 on Linux and Python 3.5 on Windows7.

Line 597 in _pyrapidjson.cpp is where the error is generated.  I checked the filehandle.fileno() and it returns an integer as expected.  It also doesn't appear to matter if one uses io.open() or just the built-in open().  Any thoughts, it looks like PyObject_AsFileDescriptor isn't working properly, or perhaps the problem is with the tuple parsing?

**Comment by hhatto** [comment]
umm...

I tried the same script you used, but couldn't reproduce it.

```
import rapidjson
data = { 'foo': 'bar' }
with open( 'tempfile.json', 'w' ) as fh:
    print( fh.fileno() )
    rapidjson.dump( data, fh )
```

```
$ python testrapid.py
3
$ cat tempfile.json
{"foo":"bar"}
```

Tested on Python 3.4.5 on Linux.
Sorry, I can not try it on Windows environment.

**Comment by robbmcleod** [comment]
Hi, thanks for the fast response.  Sorry, I simplified my example too much, here's a working error-generating code:

    import rapidjson, io
    stream = io.StringIO()
    data = { 'foo':'bar' }
    rapidjson.dump( data, stream )

I see now that your stream interface is essentially Python2 so you don't really support Python3's IO interface, as every stream is assumed to be a file.  I can workaround the problem by using `dumps()`.  The objective here was to use the `blosc` library to compress the JSON before writing to disk, for which I was using Python3 streams:

http://entropyproduction.blogspot.ch/2016/12/bloscpickle.html

**Comment by hhatto** [comment]
> Hi, thanks for the fast response.  Sorry, I simplified my example too much, here's a working error-generating code:
> 
>     import rapidjson, io
>     stream = io.StringIO()
>     data = { 'foo':'bar' }
>     rapidjson.dump( data, stream )

Oh right 😄 
Please wait a little as it will fix it.

**Comment by hhatto** [comment]
fix in master branch.

**Comment by robbmcleod** [comment]
Thanks!

**Comment by hhatto** [comment]
version 0.5 has been released.

https://pypi.python.org/pypi/pyrapidjson/0.5

use rapidjson latest version. (v1.1)
