### ISSUE TITLE
Getting segfaults on dumps with Unicode data

### ISSUE THREAD

**Issue by dsuch** [hhatto/pyrapidjson#20]
Hello,

I'm using pyrapidjson 0.5. Please consider the snippet below. It will segfault when run with Python 2.7.6 64-bit on Ubuntu 16.04.

The way to work around it is to .encode data before it's passed to .dumps, e.g. to use data.encode('utf-8').

I understand that pyrapidjson may prefer to work with strings in explicit encodings but can you please make it handle Unicode input gracefully? A TypeError if something is not a string would be appreciated.

Thanks a lot!

```python
# -*- coding: utf-8 -*-

from rapidjson import dumps

data = u'演示'

out = dumps({'data':data})
print(out)
```

**Comment by hhatto** [comment]
Thanks for bug reporting.

fix 8562dab68ca5017efd3699cf7aa3d0c96b15b133

Could you try once on current master branch?

**Comment by hhatto** [comment]
[version 0.5.1](https://pypi.python.org/pypi/pyrapidjson/0.5.1) has been released

**Comment by dsuch** [comment]
Thanks, I can confirm that 0.5.1 solves it.
