### ISSUE TITLE
segfaults on tuple objects

### ISSUE THREAD

**Issue by robbmcleod** [hhatto/pyrapidjson#21]
Howdy,

Passing a tuple to rapidjson causes a seg-fault on every platform I've tested on.

    import rapidjson as json
    testTup = ('foo','bar',55,4.67)
    jsonizedList = json.dumps( list(testTup) )
    print( jsonizedList )
    jsonizedTup = json.dumps(testTup)
    print( jsonizedTup )

Tested on: Python 2.7 (MSVC2008), 3.6 (MSVC2015), and 3.4 (gcc 4.4.47).  There's a number of use-cases where tuples are preferable to lists (i.e. they are hashable).  It would be nice if `dumps()` could take any iterable and turn it into a JSON list. A simple example would be,

    json.dumps( range(5) )

which works in `ujson` but not the native library or your port.  Generally other serializers give an option for the `dump()` and 'dumps()` functions to return lists or tuples. I.e. message pack (https://pypi.python.org/pypi/msgpack-python):

    >>> msgpack.unpackb(b'\x93\x01\x02\x03', use_list=False)

**Comment by hhatto** [comment]
Thanks for the report.

fix in 96d8d938db591b36d480bd4c083f52a9a7f954f3.

Could you try once on current master branch?

**Comment by robbmcleod** [comment]
@hhatto looks good on my end, thanks for the quick fix.

**Comment by hhatto** [comment]
version [0.5.1](https://pypi.python.org/pypi/pyrapidjson/0.5.1) has been released.
